In [42]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [34]:
df = pd.read_csv("HR_comma_sep.csv")

In [35]:
df_copy = df.copy()

df_copy['salary'] = df_copy['salary'].map({'low':0,'medium':1, 'high':2})



In [37]:
df_copy.columns
df_copy.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  sales  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0       0  
1       1  
2       1  
3       0  
4       0

In [40]:
department = df_copy['sales']
print(department[0:10])

0    sales
1    sales
2    sales
3    sales
4    sales
5    sales
6    sales
7    sales
8    sales
9    sales
Name: sales, dtype: object


In [48]:
label_encoder = LabelEncoder()
dept_int_enc = label_encoder.fit_transform(department)
print(dept_int_enc[0:10]onehot_encoder = OneHotEncoder(sparse=False)


[7 7 7 7 7 7 7 7 7 7]


In [50]:
onehot_encoder = OneHotEncoder(sparse=False)
dept_int_enc = dept_int_enc.reshape(len(dept_int_enc), 1)
onehot_encoded = onehot_encoder.fit_transform(dept_int_enc)
print(onehot_encoded[0:100])

[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  

In [58]:
df_copy['department'] = onehot_encoded

ValueError: Wrong number of items passed 10, placement implies 1

In [64]:
df_copy = df_copy.drop(['sales'],axis=1)


In [ ]:
np.any(np.isnan(mat))

In [66]:
final_pd = df_copy.join((pd.get_dummies(df['sales'])))
final_pd.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  salary  IT  \
0                   3              0     1                      0       0   0   
1                   6              0     1                      0       1   0   
2                   4              0     1                      0       1   0   
3                   5              0     1                      0       0   0   
4                   3              0     1                      0       0   0   

   RandD  accounting  hr  management  marketing  product_mng  sales  support  \
0      0           0   0           0          0            0      1        0   
1      0           0   0           0          0            0      1        0   
2      0           0   0           0          0            0      1        0   
3      0           0   0           0          0            0      1        0   
4      0           0   0           0          0            0      1        0   

   technical  
0          0  
1          0  
2          0  
3          0  
4          0

In [72]:
from sklearn.model_selection import train_test_split

Y = final_pd['left']
X = final_pd.drop(['left'],axis=1)

In [74]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, random_state=1)

In [76]:
from sklearn import tree

model = tree.DecisionTreeClassifier()

In [77]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [82]:
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
from io import StringIO

dot_data = StringIO()
export_graphviz(model, out_file=dot_data,  
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [83]:
! dot -Tpng dot_data -o tree_titanic.png

Error: dot: can't open dot_data
